<?php

namespace App\Services;

class IconService
{
    /**
     * Get all available icons
     */
    public static function getIcons(): array
    {
        return [
            // Common Icons
            'o-home',
            'o-user',
            'o-users',
            'o-cog',
            'o-star',
            'o-heart',
            'o-bell',
            'o-envelope',
            'o-phone',
            'o-map-pin',
            'o-calendar',
            'o-clock',
            'o-camera',
            'o-photo',
            'o-video-camera',
            'o-film',
            'o-microphone',

            // Action Icons
            'o-magnifying-glass',
            'o-plus',
            'o-minus',
            'o-check',
            'o-x-mark',
            'o-trash',
            'o-pencil',
            'o-pencil-square',
            'o-document',
            'o-document-text',
            'o-folder',
            'o-folder-open',
            'o-archive-box',
            'o-inbox',
            'o-paper-clip',
            'o-link',
            'o-share',
            'o-cloud',
            'o-cloud-arrow-up',
            'o-cloud-arrow-down',

            // Navigation Icons
            'o-arrow-right',
            'o-arrow-left',
            'o-arrow-up',
            'o-arrow-down',
            'o-chevron-right',
            'o-chevron-left',
            'o-chevron-up',
            'o-chevron-down',
            'o-chevron-double-right',
            'o-chevron-double-left',
            'o-chevron-double-up',
            'o-chevron-double-down',
            'o-bars-3',
            'o-bars-4',
            'o-ellipsis-horizontal',
            'o-ellipsis-vertical',

            // Social & Communication
            'o-chat-bubble-left',
            'o-chat-bubble-left-right',
            'o-chat-bubble-oval-left',
            'o-chat-bubble-bottom-center',
            'o-megaphone',
            'o-speaker-wave',
            'o-at-symbol',
            'o-hashtag',
            'o-rss',

            // Business & Finance
            'o-briefcase',
            'o-building-office',
            'o-building-office-2',
            'o-building-storefront',
            'o-shopping-bag',
            'o-shopping-cart',
            'o-credit-card',
            'o-banknotes',
            'o-currency-dollar',
            'o-currency-euro',
            'o-currency-pound',
            'o-currency-yen',
            'o-receipt-percent',
            'o-ticket',
            'o-tag',
            'o-gift',
            'o-gift-top',

            // Travel & Places
            'o-map',
            'o-globe-alt',
            'o-globe-americas',
            'o-globe-asia-australia',
            'o-globe-europe-africa',
            'o-building-library',
            'o-home-modern',
            'o-rocket-launch',
            'o-truck',
            'o-paper-airplane',

            // Weather & Nature
            'o-sun',
            'o-moon',
            'o-fire',
            'o-bolt',
            'o-cloud',
            'o-sparkles',
            'o-light-bulb',
            'o-beaker',

            // Food & Drink
            'o-cake',

            // Sports & Activities
            'o-trophy',
            'o-academic-cap',
            'o-puzzle-piece',
            'o-wrench',
            'o-wrench-screwdriver',
            'o-paint-brush',
            'o-scissors',

            // Medical & Health
            'o-shield-check',
            'o-shield-exclamation',
            'o-hand-raised',
            'o-hand-thumb-up',
            'o-hand-thumb-down',
            'o-face-smile',
            'o-face-frown',

            // Technology & Devices
            'o-computer-desktop',
            'o-device-phone-mobile',
            'o-device-tablet',
            'o-tv',
            'o-printer',
            'o-wifi',
            'o-signal',
            'o-battery-50',
            'o-battery-0',
            'o-battery-100',
            'o-power',
            'o-cpu-chip',
            'o-server',
            'o-server-stack',
            'o-code-bracket',
            'o-code-bracket-square',
            'o-command-line',
            'o-window',
            'o-bug-ant',

            // Media & Editing
            'o-play',
            'o-pause',
            'o-stop',
            'o-forward',
            'o-backward',
            'o-speaker-x-mark',
            'o-arrows-pointing-in',
            'o-arrows-pointing-out',
            'o-arrows-up-down',
            'o-arrows-right-left',
            'o-viewfinder-circle',
            'o-eye',
            'o-eye-slash',
            'o-eye-dropper',
            'o-swatch',

            // Status & Alerts
            'o-information-circle',
            'o-question-mark-circle',
            'o-exclamation-circle',
            'o-exclamation-triangle',
            'o-check-circle',
            'o-x-circle',
            'o-minus-circle',
            'o-plus-circle',
            'o-no-symbol',
            'o-bell-alert',
            'o-bell-slash',
            'o-flag',

            // Text & Typography
            'o-book-open',
            'o-bookmark',
            'o-bookmark-square',
            'o-language',
            'o-newspaper',
            'o-clipboard',
            'o-clipboard-document',
            'o-clipboard-document-list',
            'o-clipboard-document-check',
            'o-presentation-chart-bar',
            'o-presentation-chart-line',
            'o-chart-bar',
            'o-chart-pie',
            'o-calculator',
            'o-table-cells',
            'o-list-bullet',
            'o-numbered-list',
            'o-squares-2x2',
            'o-squares-plus',
            'o-queue-list',

            // Security & Privacy
            'o-lock-closed',
            'o-lock-open',
            'o-key',
            'o-finger-print',
            'o-identification',
            'o-qr-code',

            // Time & Schedule
            'o-calendar-days',
            'o-calendar-date-range',

            // Misc
            'o-adjustments-horizontal',
            'o-adjustments-vertical',
            'o-funnel',
            'o-variable',
            'o-cube',
            'o-cube-transparent',
            'o-square-2-stack',
            'o-square-3-stack-3d',
            'o-lifebuoy',
            'o-light-bulb',
            'o-magnifying-glass-circle',
            'o-magnifying-glass-plus',
            'o-magnifying-glass-minus',

            // Solid variants (s- prefix)
            's-home',
            's-user',
            's-users',
            's-cog',
            's-star',
            's-heart',
            's-bell',
            's-envelope',
            's-phone',
            's-map-pin',
            's-calendar',
            's-clock',
            's-camera',
            's-photo',
            's-video-camera',
            's-film',
            's-microphone',
            's-magnifying-glass',
            's-plus',
            's-minus',
            's-check',
            's-x-mark',
            's-trash',
            's-pencil',
            's-pencil-square',
            's-document',
            's-document-text',
            's-folder',
            's-folder-open',
            's-archive-box',
            's-inbox',
            's-paper-clip',
            's-link',
            's-share',
            's-cloud',
            's-cloud-arrow-up',
            's-cloud-arrow-down',
            's-arrow-right',
            's-arrow-left',
            's-arrow-up',
            's-arrow-down',
            's-chevron-right',
            's-chevron-left',
            's-chevron-up',
            's-chevron-down',
            's-bars-3',
            's-bars-4',
            's-chat-bubble-left',
            's-chat-bubble-left-right',
            's-megaphone',
            's-speaker-wave',
            's-at-symbol',
            's-hashtag',
            's-briefcase',
            's-building-office',
            's-building-office-2',
            's-building-storefront',
            's-shopping-bag',
            's-shopping-cart',
            's-credit-card',
            's-banknotes',
            's-currency-dollar',
            's-tag',
            's-gift',
            's-map',
            's-globe-alt',
            's-building-library',
            's-home-modern',
            's-rocket-launch',
            's-truck',
            's-paper-airplane',
            's-sun',
            's-moon',
            's-fire',
            's-bolt',
            's-sparkles',
            's-light-bulb',
            's-beaker',
            's-cake',
            's-trophy',
            's-academic-cap',
            's-puzzle-piece',
            's-wrench',
            's-wrench-screwdriver',
            's-paint-brush',
            's-scissors',
            's-shield-check',
            's-shield-exclamation',
            's-hand-raised',
            's-hand-thumb-up',
            's-hand-thumb-down',
            's-face-smile',
            's-face-frown',
            's-computer-desktop',
            's-device-phone-mobile',
            's-device-tablet',
            's-tv',
            's-printer',
            's-wifi',
            's-signal',
            's-power',
            's-cpu-chip',
            's-server',
            's-server-stack',
            's-code-bracket',
            's-code-bracket-square',
            's-command-line',
            's-bug-ant',
            's-play',
            's-pause',
            's-stop',
            's-forward',
            's-backward',
            's-eye',
            's-eye-slash',
            's-eye-dropper',
            's-swatch',
            's-information-circle',
            's-question-mark-circle',
            's-exclamation-circle',
            's-exclamation-triangle',
            's-check-circle',
            's-x-circle',
            's-minus-circle',
            's-plus-circle',
            's-no-symbol',
            's-bell-alert',
            's-bell-slash',
            's-flag',
            's-book-open',
            's-bookmark',
            's-bookmark-square',
            's-language',
            's-newspaper',
            's-clipboard',
            's-clipboard-document',
            's-clipboard-document-list',
            's-clipboard-document-check',
            's-presentation-chart-bar',
            's-presentation-chart-line',
            's-chart-bar',
            's-chart-pie',
            's-calculator',
            's-table-cells',
            's-list-bullet',
            's-squares-2x2',
            's-squares-plus',
            's-lock-closed',
            's-lock-open',
            's-key',
            's-finger-print',
            's-identification',
            's-qr-code',
            's-calendar-days',
            's-adjustments-horizontal',
            's-adjustments-vertical',
            's-funnel',
            's-cube',
            's-cube-transparent',
            's-square-2-stack',
            's-square-3-stack-3d',
            's-lifebuoy',
            's-magnifying-glass-circle',
            's-magnifying-glass-plus',
            's-magnifying-glass-minus',
        ];
    }

    /**
     * Get icon categories
     */
    public static function getCategories(): array
    {
        return [
            'common' => [
                'label' => 'Common',
                'label_ar' => 'شائعة',
                'icons' => ['o-home', 'o-user', 'o-users', 'o-cog', 'o-star', 'o-heart', 'o-bell', 'o-envelope', 'o-phone', 'o-map-pin', 'o-calendar', 'o-clock', 'o-camera', 'o-photo'],
            ],
            'actions' => [
                'label' => 'Actions',
                'label_ar' => 'إجراءات',
                'icons' => ['o-magnifying-glass', 'o-plus', 'o-minus', 'o-check', 'o-x-mark', 'o-trash', 'o-pencil', 'o-document', 'o-folder',  'o-share', 'o-link'],
            ],
            'navigation' => [
                'label' => 'Navigation',
                'label_ar' => 'تنقل',
                'icons' => ['o-arrow-right', 'o-arrow-left', 'o-arrow-up', 'o-arrow-down', 'o-chevron-right', 'o-chevron-left', 'o-chevron-up', 'o-chevron-down', 'o-bars-3'],
            ],
            'business' => [
                'label' => 'Business',
                'label_ar' => 'أعمال',
                'icons' => ['o-briefcase', 'o-building-office', 'o-shopping-bag', 'o-shopping-cart', 'o-credit-card', 'o-banknotes', 'o-currency-dollar', 'o-tag', 'o-gift'],
            ],
            'travel' => [
                'label' => 'Travel',
                'label_ar' => 'سفر',
                'icons' => ['o-map', 'o-globe-alt', 'o-building-library', 'o-home-modern', 'o-rocket-launch', 'o-truck', 'o-paper-airplane'],
            ],
            'weather' => [
                'label' => 'Weather',
                'label_ar' => 'طقس',
                'icons' => ['o-sun', 'o-moon', 'o-fire', 'o-bolt', 'o-cloud', 'o-sparkles'],
            ],
            'technology' => [
                'label' => 'Technology',
                'label_ar' => 'تقنية',
                'icons' => ['o-computer-desktop', 'o-device-phone-mobile', 'o-device-tablet', 'o-tv', 'o-printer', 'o-wifi', 'o-signal', 'o-cpu-chip', 'o-server', 'o-code-bracket'],
            ],
            'status' => [
                'label' => 'Status',
                'label_ar' => 'حالة',
                'icons' => ['o-information-circle', 'o-question-mark-circle', 'o-exclamation-circle', 'o-exclamation-triangle', 'o-check-circle', 'o-x-circle', 'o-flag'],
            ],
            'security' => [
                'label' => 'Security',
                'label_ar' => 'أمان',
                'icons' => ['o-lock-closed', 'o-lock-open', 'o-key', 'o-finger-print', 'o-shield', 'o-shield-check', 'o-shield-exclamation'],
            ],
        ];
    }
}
